DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(50) NOT NULL,
    uri varchar(350) NOT NULL,
    ip varchar(45) NOT NULL,
    created timestamp without time zone
);
